
name: myapp
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  google_sign_in: ^7.2.0

  # State Management
  provider: ^6.1.2

  # UI & Icons
  cupertino_icons: ^1.0.6
  go_router: ^16.3.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0 # Eklendi
  transparent_image: ^2.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
