
name: myapp
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Uyumlu versiyon seti)
  firebase_core: ^2.32.0
  firebase_auth: ^4.18.2
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1

  # State Management
  provider: ^6.1.2

  # UI & Icons
  cupertino_icons: ^1.0.6
  go_router: ^16.3.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0 # Eklendi
  transparent_image: ^2.0.1
  intl: ^0.20.2
  share_plus: ^9.0.0 # Sosyal medya paylaşımı için

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
